tests: bootstrap-host: Add SUSE support in the RedHat network scripts
[This is identical to Idec9d9e157422496602858b8a0761ab46f035786]

There is nothing RedHat specific in these scripts apart from the
DEVICE variable usage. As such, detect the running distro, set a new
variable, and use it in these scripts so they can be shared by both
SUSE and RedHat distributions. Moreover, the 'ip' utility may not
always be installed in the /usr/sbin directory so determine its path
during runtime.

Change-Id: Ide2491a801dcd4c43a38e4da3010887e64d79e54
(cherry picked from commit 5eb2c0096332cbb5f67db32a30c544b147ea8bf8)

diff --git a/tests/roles/bootstrap-host/templates/rpm_interface_ifdown-post.cfg.j2 b/tests/roles/bootstrap-host/templates/rpm_interface_ifdown-post.cfg.j2
--- a/tests/roles/bootstrap-host/templates/rpm_interface_ifdown-post.cfg.j2
+++ b/tests/roles/bootstrap-host/templates/rpm_interface_ifdown-post.cfg.j2
@@ -13,7 +13,17 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-if [ "${DEVICE}" == "{{ item[1].name | default('br-mgmt') }}" ]; then
-    /usr/sbin/ip link set {{ item[1].name | default('br-mgmt') }}-veth nomaster || true
-    /usr/sbin/ip link del {{ item[1].name | default('br-mgmt') }}-veth || true
+source /etc/os-release || source /usr/lib/os-release
+
+case "${ID}" in
+    *suse*) INTERFACE="${1}"; break ;;
+    centos|rhel|fedora) INTERFACE="${DEVICE}"; break ;;
+    *) echo "Unsupported distribution ${ID}"; exit 1;
+esac
+
+_ip=$(which ip 2>/dev/null || { echo "Failed to find ip executable"; exit 1; })
+
+if [ "${INTERFACE}" == "{{ item[1].name | default('br-mgmt') }}" ]; then
+    eval $_ip link set {{ item[1].name | default('br-mgmt') }}-veth nomaster || true
+    eval $_ip link del {{ item[1].name | default('br-mgmt') }}-veth || true
 fi
diff --git a/tests/roles/bootstrap-host/templates/rpm_interface_ifup-post.cfg.j2 b/tests/roles/bootstrap-host/templates/rpm_interface_ifup-post.cfg.j2
--- a/tests/roles/bootstrap-host/templates/rpm_interface_ifup-post.cfg.j2
+++ b/tests/roles/bootstrap-host/templates/rpm_interface_ifup-post.cfg.j2
@@ -13,13 +13,23 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-if [ "${DEVICE}" == "{{ item[1].name | default('br-mgmt') }}" ]; then
+source /etc/os-release || source /usr/lib/os-release
+
+case "${ID}" in
+    *suse*) INTERFACE="${1}"; break ;;
+    centos|rhel|fedora) INTERFACE="${DEVICE}"; break ;;
+    *) echo "Unsupported distribution ${ID}"; exit 1;
+esac
+
+_ip=$(which ip 2>/dev/null || { echo "Failed to find ip executable"; exit 1; })
+
+if [ "${INTERFACE}" == "{{ item[1].name | default('br-mgmt') }}" ]; then
     # Create veth pair, don't bomb if already exists
     echo "Creating veth"
-    /usr/sbin/ip link add {{ item[1].name | default('br-mgmt') }}-veth type veth peer name {{ item[1].veth_peer | default('eth0') }} || true
+    eval $_ip link add {{ item[1].name | default('br-mgmt') }}-veth type veth peer name {{ item[1].veth_peer | default('eth0') }} || true
     # Set both ends UP
-    /usr/sbin/ip link set {{ item[1].name | default('br-mgmt') }}-veth up || true
-    /usr/sbin/ip link set {{ item[1].veth_peer | default('eth0') }} up || true
+    eval $_ip link set {{ item[1].name | default('br-mgmt') }}-veth up || true
+    eval $_ip link set {{ item[1].veth_peer | default('eth0') }} up || true
     # add eth12 to the bridge
-    /usr/sbin/ip link set {{ item[1].name | default('br-mgmt') }}-veth master {{ item[1].name | default('br-mgmt') }} || true
+    eval $_ip link set {{ item[1].name | default('br-mgmt') }}-veth master {{ item[1].name | default('br-mgmt') }} || true
 fi
